[project]
name = "mcp-use-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-anthropic>=0.3.13",
    "mcp-use>=1.2.12",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
